### PR TITLE
Initial PR

### PR DESCRIPTION
**Pull request by katzhang-ias**
Please note that this is an initial PR to verify we are on the right track.

Done
* Made IAS request and parsed the response for slot-level keyword targeting

To do:
* Diagnostic pixels for IAS to track/debug

### CODE REVIEW

**Comment by katzhang-ias** [comment]
Hi @ix-certification ,

I'm looking at the new documentation in development-v2 branch (https://github.com/indexexchange/integral-ad-science-adapter/tree/development-v2). Is it right to say the test page (https://github.com/indexexchange/ht-wrapper-certification/blob/master/index.html) is not meant for local development any more? Thanks!

**Comment by ix-certification** [comment]
Hi @katzhang-ias !

That is correct. The new template does not use the test page previously provided. The modules have been rewritten to be more modular to simply unit testing.

Let me know if you have any questions!

**Comment by katzhang-ias** [comment]
Thanks @ix-certification again for the quick response! 
Another question: I noticed in the spec that `returnParcels` only contain xSlots data from `partnerConfig` (https://github.com/indexexchange/integral-ad-science-adapter/blob/development-v2/spec/generateRequestObj.spec.js#L28). I assume I'm not supposed to change this helper function since it reflects how parcels are actually generated. How can I then access a property on partner config object other than `xSlots`?

**Comment by katzhang-ias** [comment]
Hi @ix-certification ,

Also what is the recommended way to access Google Publisher Tags? In v1 the Utilities library has API methods like `getGSlots`, which makes my integration code a lot easier but now it seems gone.

**Pull request closed without merging**
